(clear)
(load "ontologia/menus.pont")
(load "inicializacion.clp")
(load "main.clp")
(load "obtener_preferencias.clp")
(load "inferir_preferencias.clp")
(load "descartar_platos.clp")
(load "puntuar_platos.clp")
(load "crear_menus.clp")
(load "puntuar_menus.clp")
(load "escoger_menus.clp")
(reset)
(load-instances "ontologia/menus.pins")
