(define (problem menus-1)
  (:domain menus)
  (:objects
    ; Primeros
    primero0 primero1 primero2 primero3 primero4 primero5 primero6 primero7 primero8 primero9 primero10 primero11 primero12 primero13 primero14 primero15 primero16 primero17 primero18 primero19 primero20 primero21 primero22 primero23 primero24 primero25 primero26 primero27 primero28 primero29 primero30 primero31 primero32 primero33 primero34 primero35 primero36 primero37 primero38 primero39 primero40 primero41 primero42 primero43 primero44 primero45 primero46 primero47 primero48 primero49  - primero
    ; Segundos
    segundo0 segundo1 segundo2 segundo3 segundo4 segundo5 segundo6 segundo7 segundo8 segundo9 segundo10 segundo11 segundo12 segundo13 segundo14 segundo15 segundo16 segundo17 segundo18 segundo19 segundo20 segundo21 segundo22 segundo23 segundo24 segundo25 segundo26 segundo27 segundo28 segundo29 segundo30 segundo31 segundo32 segundo33 segundo34 segundo35 segundo36 segundo37 segundo38 segundo39 segundo40 segundo41 segundo42 segundo43 segundo44 segundo45 segundo46 segundo47 segundo48 segundo49  - segundo
    ; Dias
    lunes martes miercoles jueves viernes - dia
    ; tipos
    tipo0 tipo1 tipo2 tipo3 tipo4 tipo5  - tipo_plato
)
(:init

    (consecutivo lunes martes)
    (consecutivo martes miercoles)
    (consecutivo miercoles jueves)
    (consecutivo jueves viernes)
    ; No usamos este ultimo predicado porque resulta en un ciclo.
    ;(consecutivo viernes lunes)
    ; Usamos en su lugar este predicado que indica que viernes no
    ; tiene sucesor.
    (ultimo_dia viernes)

    ; NIVEL BASICO
    ; Incompatibilidades 
    (incompatible primero0 segundo3)
    (incompatible primero0 segundo5)
    (incompatible primero0 segundo8)
    (incompatible primero0 segundo14)
    (incompatible primero0 segundo16)
    (incompatible primero0 segundo17)
    (incompatible primero0 segundo18)
    (incompatible primero0 segundo25)
    (incompatible primero0 segundo28)
    (incompatible primero0 segundo29)
    (incompatible primero0 segundo38)
    (incompatible primero0 segundo47)
    (incompatible primero1 segundo0)
    (incompatible primero1 segundo4)
    (incompatible primero1 segundo11)
    (incompatible primero1 segundo15)
    (incompatible primero1 segundo21)
    (incompatible primero1 segundo23)
    (incompatible primero1 segundo30)
    (incompatible primero1 segundo33)
    (incompatible primero1 segundo37)
    (incompatible primero1 segundo38)
    (incompatible primero1 segundo39)
    (incompatible primero1 segundo43)
    (incompatible primero1 segundo46)
    (incompatible primero2 segundo8)
    (incompatible primero2 segundo12)
    (incompatible primero2 segundo20)
    (incompatible primero2 segundo26)
    (incompatible primero2 segundo32)
    (incompatible primero2 segundo42)
    (incompatible primero3 segundo1)
    (incompatible primero3 segundo13)
    (incompatible primero3 segundo20)
    (incompatible primero3 segundo28)
    (incompatible primero3 segundo32)
    (incompatible primero3 segundo39)
    (incompatible primero3 segundo42)
    (incompatible primero4 segundo3)
    (incompatible primero4 segundo4)
    (incompatible primero4 segundo14)
    (incompatible primero4 segundo16)
    (incompatible primero4 segundo19)
    (incompatible primero4 segundo20)
    (incompatible primero4 segundo23)
    (incompatible primero4 segundo28)
    (incompatible primero4 segundo29)
    (incompatible primero4 segundo32)
    (incompatible primero4 segundo39)
    (incompatible primero5 segundo10)
    (incompatible primero5 segundo11)
    (incompatible primero5 segundo14)
    (incompatible primero5 segundo16)
    (incompatible primero5 segundo23)
    (incompatible primero5 segundo30)
    (incompatible primero5 segundo32)
    (incompatible primero5 segundo44)
    (incompatible primero6 segundo2)
    (incompatible primero6 segundo6)
    (incompatible primero6 segundo7)
    (incompatible primero6 segundo9)
    (incompatible primero6 segundo10)
    (incompatible primero6 segundo12)
    (incompatible primero6 segundo13)
    (incompatible primero6 segundo20)
    (incompatible primero6 segundo26)
    (incompatible primero6 segundo32)
    (incompatible primero6 segundo49)
    (incompatible primero7 segundo4)
    (incompatible primero7 segundo6)
    (incompatible primero7 segundo7)
    (incompatible primero7 segundo8)
    (incompatible primero7 segundo17)
    (incompatible primero7 segundo23)
    (incompatible primero7 segundo24)
    (incompatible primero7 segundo34)
    (incompatible primero7 segundo35)
    (incompatible primero7 segundo42)
    (incompatible primero7 segundo45)
    (incompatible primero8 segundo5)
    (incompatible primero8 segundo14)
    (incompatible primero8 segundo15)
    (incompatible primero8 segundo20)
    (incompatible primero8 segundo26)
    (incompatible primero8 segundo34)
    (incompatible primero8 segundo37)
    (incompatible primero8 segundo38)
    (incompatible primero8 segundo46)
    (incompatible primero8 segundo47)
    (incompatible primero9 segundo4)
    (incompatible primero9 segundo14)
    (incompatible primero9 segundo21)
    (incompatible primero9 segundo25)
    (incompatible primero9 segundo39)
    (incompatible primero9 segundo43)
    (incompatible primero9 segundo48)
    (incompatible primero10 segundo4)
    (incompatible primero10 segundo5)
    (incompatible primero10 segundo15)
    (incompatible primero10 segundo16)
    (incompatible primero10 segundo22)
    (incompatible primero10 segundo41)
    (incompatible primero10 segundo44)
    (incompatible primero10 segundo46)
    (incompatible primero10 segundo47)
    (incompatible primero10 segundo48)
    (incompatible primero11 segundo2)
    (incompatible primero11 segundo4)
    (incompatible primero11 segundo5)
    (incompatible primero11 segundo13)
    (incompatible primero11 segundo14)
    (incompatible primero11 segundo15)
    (incompatible primero11 segundo23)
    (incompatible primero11 segundo33)
    (incompatible primero11 segundo36)
    (incompatible primero11 segundo40)
    (incompatible primero11 segundo42)
    (incompatible primero12 segundo9)
    (incompatible primero12 segundo12)
    (incompatible primero12 segundo14)
    (incompatible primero12 segundo23)
    (incompatible primero12 segundo25)
    (incompatible primero12 segundo33)
    (incompatible primero12 segundo34)
    (incompatible primero12 segundo35)
    (incompatible primero12 segundo37)
    (incompatible primero12 segundo46)
    (incompatible primero12 segundo47)
    (incompatible primero13 segundo0)
    (incompatible primero13 segundo8)
    (incompatible primero13 segundo14)
    (incompatible primero13 segundo15)
    (incompatible primero13 segundo19)
    (incompatible primero13 segundo21)
    (incompatible primero13 segundo23)
    (incompatible primero13 segundo24)
    (incompatible primero13 segundo25)
    (incompatible primero13 segundo33)
    (incompatible primero13 segundo44)
    (incompatible primero14 segundo2)
    (incompatible primero14 segundo3)
    (incompatible primero14 segundo6)
    (incompatible primero14 segundo9)
    (incompatible primero14 segundo12)
    (incompatible primero14 segundo19)
    (incompatible primero14 segundo23)
    (incompatible primero14 segundo25)
    (incompatible primero14 segundo30)
    (incompatible primero14 segundo32)
    (incompatible primero14 segundo36)
    (incompatible primero14 segundo47)
    (incompatible primero15 segundo0)
    (incompatible primero15 segundo1)
    (incompatible primero15 segundo4)
    (incompatible primero15 segundo16)
    (incompatible primero15 segundo22)
    (incompatible primero15 segundo24)
    (incompatible primero15 segundo29)
    (incompatible primero15 segundo30)
    (incompatible primero15 segundo31)
    (incompatible primero15 segundo32)
    (incompatible primero15 segundo34)
    (incompatible primero15 segundo40)
    (incompatible primero15 segundo41)
    (incompatible primero15 segundo46)
    (incompatible primero16 segundo5)
    (incompatible primero16 segundo9)
    (incompatible primero16 segundo15)
    (incompatible primero16 segundo18)
    (incompatible primero16 segundo23)
    (incompatible primero16 segundo49)
    (incompatible primero17 segundo1)
    (incompatible primero17 segundo8)
    (incompatible primero17 segundo12)
    (incompatible primero17 segundo18)
    (incompatible primero17 segundo28)
    (incompatible primero17 segundo36)
    (incompatible primero17 segundo45)
    (incompatible primero17 segundo47)
    (incompatible primero17 segundo49)
    (incompatible primero18 segundo8)
    (incompatible primero18 segundo20)
    (incompatible primero18 segundo22)
    (incompatible primero18 segundo23)
    (incompatible primero18 segundo28)
    (incompatible primero18 segundo31)
    (incompatible primero18 segundo33)
    (incompatible primero18 segundo35)
    (incompatible primero18 segundo37)
    (incompatible primero18 segundo39)
    (incompatible primero19 segundo12)
    (incompatible primero19 segundo19)
    (incompatible primero19 segundo22)
    (incompatible primero19 segundo38)
    (incompatible primero19 segundo40)
    (incompatible primero19 segundo44)
    (incompatible primero20 segundo2)
    (incompatible primero20 segundo3)
    (incompatible primero20 segundo6)
    (incompatible primero20 segundo14)
    (incompatible primero20 segundo16)
    (incompatible primero20 segundo19)
    (incompatible primero20 segundo32)
    (incompatible primero20 segundo36)
    (incompatible primero20 segundo43)
    (incompatible primero20 segundo47)
    (incompatible primero21 segundo1)
    (incompatible primero21 segundo18)
    (incompatible primero21 segundo20)
    (incompatible primero21 segundo25)
    (incompatible primero21 segundo26)
    (incompatible primero21 segundo39)
    (incompatible primero21 segundo45)
    (incompatible primero21 segundo49)
    (incompatible primero22 segundo2)
    (incompatible primero22 segundo8)
    (incompatible primero22 segundo11)
    (incompatible primero22 segundo17)
    (incompatible primero22 segundo19)
    (incompatible primero22 segundo20)
    (incompatible primero22 segundo22)
    (incompatible primero22 segundo26)
    (incompatible primero22 segundo28)
    (incompatible primero22 segundo35)
    (incompatible primero22 segundo39)
    (incompatible primero22 segundo41)
    (incompatible primero22 segundo46)
    (incompatible primero23 segundo0)
    (incompatible primero23 segundo3)
    (incompatible primero23 segundo11)
    (incompatible primero23 segundo13)
    (incompatible primero23 segundo15)
    (incompatible primero23 segundo16)
    (incompatible primero23 segundo21)
    (incompatible primero23 segundo27)
    (incompatible primero23 segundo46)
    (incompatible primero24 segundo4)
    (incompatible primero24 segundo7)
    (incompatible primero24 segundo10)
    (incompatible primero24 segundo12)
    (incompatible primero24 segundo15)
    (incompatible primero24 segundo18)
    (incompatible primero24 segundo20)
    (incompatible primero24 segundo23)
    (incompatible primero24 segundo27)
    (incompatible primero24 segundo30)
    (incompatible primero24 segundo31)
    (incompatible primero24 segundo34)
    (incompatible primero24 segundo43)
    (incompatible primero24 segundo44)
    (incompatible primero24 segundo45)
    (incompatible primero24 segundo47)
    (incompatible primero25 segundo3)
    (incompatible primero25 segundo7)
    (incompatible primero25 segundo9)
    (incompatible primero25 segundo17)
    (incompatible primero25 segundo18)
    (incompatible primero25 segundo21)
    (incompatible primero25 segundo26)
    (incompatible primero25 segundo27)
    (incompatible primero25 segundo28)
    (incompatible primero25 segundo30)
    (incompatible primero25 segundo31)
    (incompatible primero25 segundo34)
    (incompatible primero25 segundo36)
    (incompatible primero25 segundo43)
    (incompatible primero25 segundo47)
    (incompatible primero26 segundo8)
    (incompatible primero26 segundo23)
    (incompatible primero26 segundo27)
    (incompatible primero26 segundo44)
    (incompatible primero27 segundo0)
    (incompatible primero27 segundo4)
    (incompatible primero27 segundo13)
    (incompatible primero27 segundo23)
    (incompatible primero27 segundo25)
    (incompatible primero27 segundo29)
    (incompatible primero27 segundo30)
    (incompatible primero27 segundo32)
    (incompatible primero27 segundo34)
    (incompatible primero27 segundo38)
    (incompatible primero28 segundo2)
    (incompatible primero28 segundo7)
    (incompatible primero28 segundo8)
    (incompatible primero28 segundo11)
    (incompatible primero28 segundo14)
    (incompatible primero28 segundo20)
    (incompatible primero28 segundo25)
    (incompatible primero28 segundo28)
    (incompatible primero28 segundo31)
    (incompatible primero28 segundo33)
    (incompatible primero28 segundo41)
    (incompatible primero28 segundo43)
    (incompatible primero28 segundo45)
    (incompatible primero29 segundo2)
    (incompatible primero29 segundo7)
    (incompatible primero29 segundo10)
    (incompatible primero29 segundo11)
    (incompatible primero29 segundo14)
    (incompatible primero29 segundo16)
    (incompatible primero29 segundo17)
    (incompatible primero29 segundo19)
    (incompatible primero29 segundo21)
    (incompatible primero29 segundo24)
    (incompatible primero29 segundo33)
    (incompatible primero29 segundo36)
    (incompatible primero29 segundo40)
    (incompatible primero29 segundo47)
    (incompatible primero30 segundo7)
    (incompatible primero30 segundo12)
    (incompatible primero30 segundo13)
    (incompatible primero30 segundo14)
    (incompatible primero30 segundo27)
    (incompatible primero30 segundo36)
    (incompatible primero30 segundo42)
    (incompatible primero30 segundo44)
    (incompatible primero30 segundo45)
    (incompatible primero30 segundo46)
    (incompatible primero30 segundo48)
    (incompatible primero31 segundo0)
    (incompatible primero31 segundo5)
    (incompatible primero31 segundo7)
    (incompatible primero31 segundo9)
    (incompatible primero31 segundo12)
    (incompatible primero31 segundo15)
    (incompatible primero31 segundo17)
    (incompatible primero31 segundo21)
    (incompatible primero31 segundo32)
    (incompatible primero31 segundo36)
    (incompatible primero31 segundo39)
    (incompatible primero31 segundo41)
    (incompatible primero32 segundo5)
    (incompatible primero32 segundo10)
    (incompatible primero32 segundo19)
    (incompatible primero32 segundo21)
    (incompatible primero32 segundo35)
    (incompatible primero32 segundo39)
    (incompatible primero32 segundo40)
    (incompatible primero32 segundo41)
    (incompatible primero32 segundo42)
    (incompatible primero33 segundo1)
    (incompatible primero33 segundo2)
    (incompatible primero33 segundo4)
    (incompatible primero33 segundo9)
    (incompatible primero33 segundo17)
    (incompatible primero33 segundo23)
    (incompatible primero33 segundo24)
    (incompatible primero33 segundo27)
    (incompatible primero33 segundo30)
    (incompatible primero33 segundo31)
    (incompatible primero33 segundo35)
    (incompatible primero33 segundo41)
    (incompatible primero34 segundo0)
    (incompatible primero34 segundo11)
    (incompatible primero34 segundo12)
    (incompatible primero34 segundo16)
    (incompatible primero34 segundo18)
    (incompatible primero34 segundo28)
    (incompatible primero34 segundo36)
    (incompatible primero34 segundo39)
    (incompatible primero34 segundo46)
    (incompatible primero34 segundo48)
    (incompatible primero35 segundo0)
    (incompatible primero35 segundo5)
    (incompatible primero35 segundo14)
    (incompatible primero35 segundo17)
    (incompatible primero35 segundo18)
    (incompatible primero35 segundo24)
    (incompatible primero35 segundo31)
    (incompatible primero35 segundo34)
    (incompatible primero35 segundo35)
    (incompatible primero35 segundo37)
    (incompatible primero35 segundo42)
    (incompatible primero35 segundo45)
    (incompatible primero35 segundo48)
    (incompatible primero36 segundo1)
    (incompatible primero36 segundo2)
    (incompatible primero36 segundo5)
    (incompatible primero36 segundo17)
    (incompatible primero36 segundo18)
    (incompatible primero36 segundo19)
    (incompatible primero36 segundo25)
    (incompatible primero36 segundo34)
    (incompatible primero36 segundo36)
    (incompatible primero36 segundo43)
    (incompatible primero36 segundo44)
    (incompatible primero37 segundo3)
    (incompatible primero37 segundo7)
    (incompatible primero37 segundo9)
    (incompatible primero37 segundo12)
    (incompatible primero37 segundo14)
    (incompatible primero37 segundo18)
    (incompatible primero37 segundo19)
    (incompatible primero37 segundo22)
    (incompatible primero37 segundo23)
    (incompatible primero37 segundo25)
    (incompatible primero37 segundo29)
    (incompatible primero37 segundo32)
    (incompatible primero37 segundo40)
    (incompatible primero37 segundo43)
    (incompatible primero37 segundo46)
    (incompatible primero37 segundo49)
    (incompatible primero38 segundo8)
    (incompatible primero38 segundo11)
    (incompatible primero38 segundo15)
    (incompatible primero38 segundo21)
    (incompatible primero38 segundo30)
    (incompatible primero38 segundo37)
    (incompatible primero38 segundo43)
    (incompatible primero39 segundo6)
    (incompatible primero39 segundo9)
    (incompatible primero39 segundo15)
    (incompatible primero39 segundo20)
    (incompatible primero39 segundo25)
    (incompatible primero39 segundo28)
    (incompatible primero39 segundo34)
    (incompatible primero39 segundo40)
    (incompatible primero39 segundo42)
    (incompatible primero39 segundo44)
    (incompatible primero39 segundo46)
    (incompatible primero40 segundo6)
    (incompatible primero40 segundo7)
    (incompatible primero40 segundo12)
    (incompatible primero40 segundo17)
    (incompatible primero40 segundo18)
    (incompatible primero40 segundo21)
    (incompatible primero40 segundo24)
    (incompatible primero40 segundo26)
    (incompatible primero40 segundo35)
    (incompatible primero40 segundo37)
    (incompatible primero40 segundo38)
    (incompatible primero40 segundo42)
    (incompatible primero41 segundo2)
    (incompatible primero41 segundo4)
    (incompatible primero41 segundo12)
    (incompatible primero41 segundo15)
    (incompatible primero41 segundo18)
    (incompatible primero41 segundo29)
    (incompatible primero41 segundo33)
    (incompatible primero41 segundo34)
    (incompatible primero41 segundo36)
    (incompatible primero41 segundo41)
    (incompatible primero41 segundo43)
    (incompatible primero41 segundo45)
    (incompatible primero41 segundo48)
    (incompatible primero42 segundo2)
    (incompatible primero42 segundo7)
    (incompatible primero42 segundo8)
    (incompatible primero42 segundo9)
    (incompatible primero42 segundo11)
    (incompatible primero42 segundo14)
    (incompatible primero42 segundo19)
    (incompatible primero42 segundo25)
    (incompatible primero42 segundo27)
    (incompatible primero42 segundo34)
    (incompatible primero42 segundo35)
    (incompatible primero42 segundo42)
    (incompatible primero42 segundo47)
    (incompatible primero43 segundo9)
    (incompatible primero43 segundo10)
    (incompatible primero43 segundo16)
    (incompatible primero43 segundo18)
    (incompatible primero43 segundo22)
    (incompatible primero43 segundo30)
    (incompatible primero43 segundo34)
    (incompatible primero43 segundo35)
    (incompatible primero43 segundo36)
    (incompatible primero43 segundo42)
    (incompatible primero43 segundo47)
    (incompatible primero44 segundo2)
    (incompatible primero44 segundo4)
    (incompatible primero44 segundo6)
    (incompatible primero44 segundo12)
    (incompatible primero44 segundo22)
    (incompatible primero44 segundo31)
    (incompatible primero44 segundo36)
    (incompatible primero44 segundo42)
    (incompatible primero45 segundo9)
    (incompatible primero45 segundo11)
    (incompatible primero45 segundo12)
    (incompatible primero45 segundo13)
    (incompatible primero45 segundo19)
    (incompatible primero45 segundo20)
    (incompatible primero45 segundo22)
    (incompatible primero45 segundo23)
    (incompatible primero45 segundo38)
    (incompatible primero45 segundo40)
    (incompatible primero45 segundo44)
    (incompatible primero45 segundo46)
    (incompatible primero45 segundo47)
    (incompatible primero46 segundo1)
    (incompatible primero46 segundo13)
    (incompatible primero46 segundo20)
    (incompatible primero46 segundo21)
    (incompatible primero46 segundo23)
    (incompatible primero46 segundo30)
    (incompatible primero46 segundo32)
    (incompatible primero46 segundo34)
    (incompatible primero46 segundo36)
    (incompatible primero46 segundo37)
    (incompatible primero47 segundo19)
    (incompatible primero47 segundo22)
    (incompatible primero47 segundo25)
    (incompatible primero47 segundo26)
    (incompatible primero47 segundo35)
    (incompatible primero47 segundo37)
    (incompatible primero47 segundo48)
    (incompatible primero47 segundo49)
    (incompatible primero48 segundo14)
    (incompatible primero48 segundo22)
    (incompatible primero48 segundo26)
    (incompatible primero48 segundo28)
    (incompatible primero48 segundo34)
    (incompatible primero48 segundo35)
    (incompatible primero49 segundo4)
    (incompatible primero49 segundo9)
    (incompatible primero49 segundo12)
    (incompatible primero49 segundo15)
    (incompatible primero49 segundo23)
    (incompatible primero49 segundo27)
    ; EXTENSION 2
    ; Tipos de los platos
    (es_de_tipo primero0 tipo5)
    (es_de_tipo primero1 tipo5)
    (es_de_tipo primero2 tipo1)
    (es_de_tipo primero3 tipo4)
    (es_de_tipo primero4 tipo5)
    (es_de_tipo primero5 tipo0)
    (es_de_tipo primero6 tipo2)
    (es_de_tipo primero7 tipo5)
    (es_de_tipo primero8 tipo3)
    (es_de_tipo primero9 tipo1)
    (es_de_tipo primero10 tipo3)
    (es_de_tipo primero11 tipo2)
    (es_de_tipo primero12 tipo0)
    (es_de_tipo primero13 tipo4)
    (es_de_tipo primero14 tipo4)
    (es_de_tipo primero15 tipo2)
    (es_de_tipo primero16 tipo0)
    (es_de_tipo primero17 tipo4)
    (es_de_tipo primero18 tipo2)
    (es_de_tipo primero19 tipo1)
    (es_de_tipo primero20 tipo3)
    (es_de_tipo primero21 tipo3)
    (es_de_tipo primero22 tipo0)
    (es_de_tipo primero23 tipo0)
    (es_de_tipo primero24 tipo0)
    (es_de_tipo primero25 tipo2)
    (es_de_tipo primero26 tipo1)
    (es_de_tipo primero27 tipo5)
    (es_de_tipo primero28 tipo3)
    (es_de_tipo primero29 tipo2)
    (es_de_tipo primero30 tipo3)
    (es_de_tipo primero31 tipo2)
    (es_de_tipo primero32 tipo5)
    (es_de_tipo primero33 tipo2)
    (es_de_tipo primero34 tipo4)
    (es_de_tipo primero35 tipo4)
    (es_de_tipo primero36 tipo3)
    (es_de_tipo primero37 tipo0)
    (es_de_tipo primero38 tipo2)
    (es_de_tipo primero39 tipo0)
    (es_de_tipo primero40 tipo1)
    (es_de_tipo primero41 tipo3)
    (es_de_tipo primero42 tipo1)
    (es_de_tipo primero43 tipo2)
    (es_de_tipo primero44 tipo1)
    (es_de_tipo primero45 tipo5)
    (es_de_tipo primero46 tipo4)
    (es_de_tipo primero47 tipo0)
    (es_de_tipo primero48 tipo1)
    (es_de_tipo primero49 tipo4)
    (es_de_tipo segundo0 tipo5)
    (es_de_tipo segundo1 tipo3)
    (es_de_tipo segundo2 tipo1)
    (es_de_tipo segundo3 tipo0)
    (es_de_tipo segundo4 tipo3)
    (es_de_tipo segundo5 tipo5)
    (es_de_tipo segundo6 tipo0)
    (es_de_tipo segundo7 tipo2)
    (es_de_tipo segundo8 tipo4)
    (es_de_tipo segundo9 tipo3)
    (es_de_tipo segundo10 tipo2)
    (es_de_tipo segundo11 tipo2)
    (es_de_tipo segundo12 tipo5)
    (es_de_tipo segundo13 tipo5)
    (es_de_tipo segundo14 tipo4)
    (es_de_tipo segundo15 tipo3)
    (es_de_tipo segundo16 tipo4)
    (es_de_tipo segundo17 tipo5)
    (es_de_tipo segundo18 tipo1)
    (es_de_tipo segundo19 tipo4)
    (es_de_tipo segundo20 tipo0)
    (es_de_tipo segundo21 tipo2)
    (es_de_tipo segundo22 tipo5)
    (es_de_tipo segundo23 tipo5)
    (es_de_tipo segundo24 tipo2)
    (es_de_tipo segundo25 tipo4)
    (es_de_tipo segundo26 tipo2)
    (es_de_tipo segundo27 tipo4)
    (es_de_tipo segundo28 tipo4)
    (es_de_tipo segundo29 tipo4)
    (es_de_tipo segundo30 tipo2)
    (es_de_tipo segundo31 tipo4)
    (es_de_tipo segundo32 tipo5)
    (es_de_tipo segundo33 tipo3)
    (es_de_tipo segundo34 tipo4)
    (es_de_tipo segundo35 tipo2)
    (es_de_tipo segundo36 tipo2)
    (es_de_tipo segundo37 tipo4)
    (es_de_tipo segundo38 tipo2)
    (es_de_tipo segundo39 tipo1)
    (es_de_tipo segundo40 tipo5)
    (es_de_tipo segundo41 tipo2)
    (es_de_tipo segundo42 tipo1)
    (es_de_tipo segundo43 tipo4)
    (es_de_tipo segundo44 tipo1)
    (es_de_tipo segundo45 tipo3)
    (es_de_tipo segundo46 tipo1)
    (es_de_tipo segundo47 tipo3)
    (es_de_tipo segundo48 tipo3)
    (es_de_tipo segundo49 tipo2)
	; EXTENSION 3
    ; Esto se debe hacer por cada plato que deseemos fijar a un dia
    ; en este caso obligaremos a hacer un primero y un segundo un dia de la semana
    (servido_primero jueves)
    (menu_primero jueves primero9)
    (tipo_dia_primero jueves tipo1)
    (preparado primero9)
    (servido_segundo miercoles)
    (menu_segundo miercoles segundo10)
    (tipo_dia_segundo miercoles tipo2)
    (preparado segundo10)
	; EXTENSION 4
    ; Calorias de los primeros platos
    (= (calorias primero0) 1280)
    (= (calorias primero1) 1234)
    (= (calorias primero2) 1244)
    (= (calorias primero3) 1019)
    (= (calorias primero4) 619)
    (= (calorias primero5) 1291)
    (= (calorias primero6) 1446)
    (= (calorias primero7) 1200)
    (= (calorias primero8) 1175)
    (= (calorias primero9) 1104)
    (= (calorias primero10) 694)
    (= (calorias primero11) 1151)
    (= (calorias primero12) 1382)
    (= (calorias primero13) 1113)
    (= (calorias primero14) 961)
    (= (calorias primero15) 692)
    (= (calorias primero16) 988)
    (= (calorias primero17) 589)
    (= (calorias primero18) 702)
    (= (calorias primero19) 611)
    (= (calorias primero20) 900)
    (= (calorias primero21) 1128)
    (= (calorias primero22) 1154)
    (= (calorias primero23) 1485)
    (= (calorias primero24) 668)
    (= (calorias primero25) 649)
    (= (calorias primero26) 1273)
    (= (calorias primero27) 1174)
    (= (calorias primero28) 1470)
    (= (calorias primero29) 603)
    (= (calorias primero30) 1284)
    (= (calorias primero31) 940)
    (= (calorias primero32) 1027)
    (= (calorias primero33) 1027)
    (= (calorias primero34) 1459)
    (= (calorias primero35) 836)
    (= (calorias primero36) 508)
    (= (calorias primero37) 1094)
    (= (calorias primero38) 536)
    (= (calorias primero39) 1183)
    (= (calorias primero40) 1388)
    (= (calorias primero41) 730)
    (= (calorias primero42) 834)
    (= (calorias primero43) 1270)
    (= (calorias primero44) 1034)
    (= (calorias primero45) 1295)
    (= (calorias primero46) 1152)
    (= (calorias primero47) 1212)
    (= (calorias primero48) 1075)
    (= (calorias primero49) 1354)

    ; Calorias de los segundos platos
    (= (calorias segundo0) 1014)
    (= (calorias segundo1) 1165)
    (= (calorias segundo2) 981)
    (= (calorias segundo3) 667)
    (= (calorias segundo4) 1149)
    (= (calorias segundo5) 839)
    (= (calorias segundo6) 507)
    (= (calorias segundo7) 922)
    (= (calorias segundo8) 513)
    (= (calorias segundo9) 1477)
    (= (calorias segundo10) 715)
    (= (calorias segundo11) 1297)
    (= (calorias segundo12) 916)
    (= (calorias segundo13) 932)
    (= (calorias segundo14) 514)
    (= (calorias segundo15) 564)
    (= (calorias segundo16) 1269)
    (= (calorias segundo17) 1213)
    (= (calorias segundo18) 849)
    (= (calorias segundo19) 1305)
    (= (calorias segundo20) 895)
    (= (calorias segundo21) 736)
    (= (calorias segundo22) 1225)
    (= (calorias segundo23) 919)
    (= (calorias segundo24) 1196)
    (= (calorias segundo25) 1449)
    (= (calorias segundo26) 714)
    (= (calorias segundo27) 847)
    (= (calorias segundo28) 1161)
    (= (calorias segundo29) 979)
    (= (calorias segundo30) 1391)
    (= (calorias segundo31) 674)
    (= (calorias segundo32) 643)
    (= (calorias segundo33) 561)
    (= (calorias segundo34) 531)
    (= (calorias segundo35) 1293)
    (= (calorias segundo36) 901)
    (= (calorias segundo37) 538)
    (= (calorias segundo38) 1405)
    (= (calorias segundo39) 604)
    (= (calorias segundo40) 515)
    (= (calorias segundo41) 1310)
    (= (calorias segundo42) 1091)
    (= (calorias segundo43) 621)
    (= (calorias segundo44) 741)
    (= (calorias segundo45) 795)
    (= (calorias segundo46) 1377)
    (= (calorias segundo47) 509)
    (= (calorias segundo48) 507)
    (= (calorias segundo49) 1416)
	; EXTENSION 5
    ; Precios de los primeros platos
    (= (precio_plato primero0) 11)
    (= (precio_plato primero1) 3)
    (= (precio_plato primero2) 11)
    (= (precio_plato primero3) 5)
    (= (precio_plato primero4) 2)
    (= (precio_plato primero5) 13)
    (= (precio_plato primero6) 14)
    (= (precio_plato primero7) 12)
    (= (precio_plato primero8) 5)
    (= (precio_plato primero9) 8)
    (= (precio_plato primero10) 3)
    (= (precio_plato primero11) 5)
    (= (precio_plato primero12) 6)
    (= (precio_plato primero13) 12)
    (= (precio_plato primero14) 6)
    (= (precio_plato primero15) 0)
    (= (precio_plato primero16) 6)
    (= (precio_plato primero17) 2)
    (= (precio_plato primero18) 0)
    (= (precio_plato primero19) 0)
    (= (precio_plato primero20) 6)
    (= (precio_plato primero21) 4)
    (= (precio_plato primero22) 7)
    (= (precio_plato primero23) 1)
    (= (precio_plato primero24) 8)
    (= (precio_plato primero25) 3)
    (= (precio_plato primero26) 14)
    (= (precio_plato primero27) 4)
    (= (precio_plato primero28) 14)
    (= (precio_plato primero29) 12)
    (= (precio_plato primero30) 4)
    (= (precio_plato primero31) 10)
    (= (precio_plato primero32) 7)
    (= (precio_plato primero33) 7)
    (= (precio_plato primero34) 0)
    (= (precio_plato primero35) 9)
    (= (precio_plato primero36) 5)
    (= (precio_plato primero37) 7)
    (= (precio_plato primero38) 14)
    (= (precio_plato primero39) 11)
    (= (precio_plato primero40) 0)
    (= (precio_plato primero41) 2)
    (= (precio_plato primero42) 8)
    (= (precio_plato primero43) 7)
    (= (precio_plato primero44) 14)
    (= (precio_plato primero45) 6)
    (= (precio_plato primero46) 14)
    (= (precio_plato primero47) 12)
    (= (precio_plato primero48) 1)
    (= (precio_plato primero49) 6)
    ; Precios de los primeros platos
    (= (precio_plato segundo0) 12)
    (= (precio_plato segundo1) 7)
    (= (precio_plato segundo2) 3)
    (= (precio_plato segundo3) 11)
    (= (precio_plato segundo4) 0)
    (= (precio_plato segundo5) 11)
    (= (precio_plato segundo6) 0)
    (= (precio_plato segundo7) 0)
    (= (precio_plato segundo8) 7)
    (= (precio_plato segundo9) 6)
    (= (precio_plato segundo10) 4)
    (= (precio_plato segundo11) 11)
    (= (precio_plato segundo12) 1)
    (= (precio_plato segundo13) 11)
    (= (precio_plato segundo14) 3)
    (= (precio_plato segundo15) 9)
    (= (precio_plato segundo16) 5)
    (= (precio_plato segundo17) 1)
    (= (precio_plato segundo18) 1)
    (= (precio_plato segundo19) 4)
    (= (precio_plato segundo20) 4)
    (= (precio_plato segundo21) 1)
    (= (precio_plato segundo22) 14)
    (= (precio_plato segundo23) 4)
    (= (precio_plato segundo24) 0)
    (= (precio_plato segundo25) 13)
    (= (precio_plato segundo26) 10)
    (= (precio_plato segundo27) 6)
    (= (precio_plato segundo28) 3)
    (= (precio_plato segundo29) 3)
    (= (precio_plato segundo30) 13)
    (= (precio_plato segundo31) 0)
    (= (precio_plato segundo32) 3)
    (= (precio_plato segundo33) 1)
    (= (precio_plato segundo34) 12)
    (= (precio_plato segundo35) 3)
    (= (precio_plato segundo36) 4)
    (= (precio_plato segundo37) 4)
    (= (precio_plato segundo38) 3)
    (= (precio_plato segundo39) 11)
    (= (precio_plato segundo40) 10)
    (= (precio_plato segundo41) 7)
    (= (precio_plato segundo42) 14)
    (= (precio_plato segundo43) 3)
    (= (precio_plato segundo44) 10)
    (= (precio_plato segundo45) 9)
    (= (precio_plato segundo46) 12)
    (= (precio_plato segundo47) 1)
    (= (precio_plato segundo48) 10)
    (= (precio_plato segundo49) 5)

    (= (precio_total) 0)


    )

  (:metric 
    minimize (precio_total)
    )

  (:goal (forall (?d - dia)
                 (and (servido_primero ?d)
                      (servido_segundo ?d)
                      )
                 )
         )
  )
