(define (problem menus-1)
  (:domain menus)
  (:objects
    ; Primeros
    primero0 primero1 primero2 primero3 primero4 primero5 primero6 primero7 primero8 primero9 primero10 primero11 primero12 primero13 primero14 primero15 primero16 primero17 primero18 primero19 primero20 primero21 primero22 primero23 primero24 primero25 primero26 primero27 primero28 primero29 primero30 primero31 primero32 primero33 primero34 primero35 primero36 primero37 primero38 primero39 primero40 primero41 primero42 primero43 primero44 primero45 primero46 primero47 primero48 primero49  - primero
    ; Segundos
    segundo0 segundo1 segundo2 segundo3 segundo4 segundo5 segundo6 segundo7 segundo8 segundo9 segundo10 segundo11 segundo12 segundo13 segundo14 segundo15 segundo16 segundo17 segundo18 segundo19 segundo20 segundo21 segundo22 segundo23 segundo24 segundo25 segundo26 segundo27 segundo28 segundo29 segundo30 segundo31 segundo32 segundo33 segundo34 segundo35 segundo36 segundo37 segundo38 segundo39 segundo40 segundo41 segundo42 segundo43 segundo44 segundo45 segundo46 segundo47 segundo48 segundo49  - segundo
    ; Dias
    lunes martes miercoles jueves viernes - dia
    ; tipos
    tipo0 tipo1 tipo2 tipo3 tipo4 tipo5  - tipo_plato
)
(:init

    (consecutivo lunes martes)
    (consecutivo martes miercoles)
    (consecutivo miercoles jueves)
    (consecutivo jueves viernes)
    ; No usamos este ultimo predicado porque resulta en un ciclo.
    ;(consecutivo viernes lunes)
    ; Usamos en su lugar este predicado que indica que viernes no
    ; tiene sucesor.
    (ultimo_dia viernes)

    ; NIVEL BASICO
    ; Incompatibilidades 
    (incompatible primero0 segundo6)
    (incompatible primero0 segundo7)
    (incompatible primero0 segundo20)
    (incompatible primero0 segundo21)
    (incompatible primero0 segundo22)
    (incompatible primero0 segundo26)
    (incompatible primero0 segundo27)
    (incompatible primero0 segundo35)
    (incompatible primero0 segundo41)
    (incompatible primero0 segundo48)
    (incompatible primero1 segundo1)
    (incompatible primero1 segundo9)
    (incompatible primero1 segundo10)
    (incompatible primero1 segundo14)
    (incompatible primero1 segundo21)
    (incompatible primero1 segundo26)
    (incompatible primero1 segundo28)
    (incompatible primero1 segundo29)
    (incompatible primero1 segundo30)
    (incompatible primero1 segundo33)
    (incompatible primero1 segundo38)
    (incompatible primero1 segundo42)
    (incompatible primero1 segundo43)
    (incompatible primero1 segundo47)
    (incompatible primero2 segundo7)
    (incompatible primero2 segundo9)
    (incompatible primero2 segundo20)
    (incompatible primero2 segundo29)
    (incompatible primero2 segundo33)
    (incompatible primero2 segundo46)
    (incompatible primero2 segundo48)
    (incompatible primero3 segundo1)
    (incompatible primero3 segundo6)
    (incompatible primero3 segundo7)
    (incompatible primero3 segundo13)
    (incompatible primero3 segundo24)
    (incompatible primero3 segundo25)
    (incompatible primero3 segundo26)
    (incompatible primero3 segundo31)
    (incompatible primero3 segundo32)
    (incompatible primero3 segundo39)
    (incompatible primero3 segundo48)
    (incompatible primero4 segundo9)
    (incompatible primero4 segundo19)
    (incompatible primero4 segundo20)
    (incompatible primero4 segundo24)
    (incompatible primero4 segundo39)
    (incompatible primero4 segundo47)
    (incompatible primero5 segundo0)
    (incompatible primero5 segundo4)
    (incompatible primero5 segundo8)
    (incompatible primero5 segundo10)
    (incompatible primero5 segundo21)
    (incompatible primero5 segundo24)
    (incompatible primero5 segundo26)
    (incompatible primero5 segundo27)
    (incompatible primero5 segundo33)
    (incompatible primero5 segundo40)
    (incompatible primero5 segundo44)
    (incompatible primero6 segundo0)
    (incompatible primero6 segundo2)
    (incompatible primero6 segundo7)
    (incompatible primero6 segundo8)
    (incompatible primero6 segundo12)
    (incompatible primero6 segundo17)
    (incompatible primero6 segundo18)
    (incompatible primero6 segundo22)
    (incompatible primero6 segundo26)
    (incompatible primero6 segundo27)
    (incompatible primero6 segundo30)
    (incompatible primero6 segundo34)
    (incompatible primero6 segundo37)
    (incompatible primero6 segundo41)
    (incompatible primero6 segundo42)
    (incompatible primero6 segundo45)
    (incompatible primero6 segundo47)
    (incompatible primero7 segundo5)
    (incompatible primero7 segundo9)
    (incompatible primero7 segundo22)
    (incompatible primero7 segundo26)
    (incompatible primero7 segundo27)
    (incompatible primero7 segundo32)
    (incompatible primero7 segundo34)
    (incompatible primero7 segundo41)
    (incompatible primero7 segundo42)
    (incompatible primero7 segundo48)
    (incompatible primero8 segundo6)
    (incompatible primero8 segundo12)
    (incompatible primero8 segundo13)
    (incompatible primero8 segundo14)
    (incompatible primero8 segundo20)
    (incompatible primero8 segundo24)
    (incompatible primero8 segundo30)
    (incompatible primero8 segundo31)
    (incompatible primero8 segundo38)
    (incompatible primero8 segundo40)
    (incompatible primero8 segundo43)
    (incompatible primero8 segundo44)
    (incompatible primero9 segundo1)
    (incompatible primero9 segundo4)
    (incompatible primero9 segundo7)
    (incompatible primero9 segundo18)
    (incompatible primero9 segundo19)
    (incompatible primero9 segundo20)
    (incompatible primero9 segundo21)
    (incompatible primero9 segundo23)
    (incompatible primero9 segundo28)
    (incompatible primero9 segundo29)
    (incompatible primero9 segundo31)
    (incompatible primero9 segundo33)
    (incompatible primero9 segundo42)
    (incompatible primero9 segundo46)
    (incompatible primero9 segundo48)
    (incompatible primero10 segundo1)
    (incompatible primero10 segundo7)
    (incompatible primero10 segundo10)
    (incompatible primero10 segundo11)
    (incompatible primero10 segundo19)
    (incompatible primero10 segundo24)
    (incompatible primero10 segundo32)
    (incompatible primero10 segundo33)
    (incompatible primero10 segundo43)
    (incompatible primero10 segundo49)
    (incompatible primero11 segundo3)
    (incompatible primero11 segundo5)
    (incompatible primero11 segundo6)
    (incompatible primero11 segundo9)
    (incompatible primero11 segundo18)
    (incompatible primero11 segundo28)
    (incompatible primero11 segundo46)
    (incompatible primero12 segundo2)
    (incompatible primero12 segundo8)
    (incompatible primero12 segundo11)
    (incompatible primero12 segundo13)
    (incompatible primero12 segundo19)
    (incompatible primero12 segundo23)
    (incompatible primero12 segundo24)
    (incompatible primero12 segundo29)
    (incompatible primero12 segundo41)
    (incompatible primero12 segundo45)
    (incompatible primero12 segundo49)
    (incompatible primero13 segundo2)
    (incompatible primero13 segundo3)
    (incompatible primero13 segundo4)
    (incompatible primero13 segundo5)
    (incompatible primero13 segundo15)
    (incompatible primero13 segundo17)
    (incompatible primero13 segundo23)
    (incompatible primero13 segundo25)
    (incompatible primero13 segundo38)
    (incompatible primero14 segundo4)
    (incompatible primero14 segundo8)
    (incompatible primero14 segundo12)
    (incompatible primero14 segundo20)
    (incompatible primero14 segundo23)
    (incompatible primero14 segundo25)
    (incompatible primero14 segundo26)
    (incompatible primero14 segundo27)
    (incompatible primero14 segundo36)
    (incompatible primero14 segundo38)
    (incompatible primero14 segundo40)
    (incompatible primero14 segundo41)
    (incompatible primero14 segundo43)
    (incompatible primero14 segundo49)
    (incompatible primero15 segundo9)
    (incompatible primero15 segundo13)
    (incompatible primero15 segundo25)
    (incompatible primero15 segundo28)
    (incompatible primero15 segundo40)
    (incompatible primero16 segundo14)
    (incompatible primero16 segundo16)
    (incompatible primero16 segundo20)
    (incompatible primero16 segundo23)
    (incompatible primero16 segundo27)
    (incompatible primero16 segundo28)
    (incompatible primero16 segundo30)
    (incompatible primero16 segundo33)
    (incompatible primero16 segundo39)
    (incompatible primero16 segundo48)
    (incompatible primero17 segundo7)
    (incompatible primero17 segundo8)
    (incompatible primero17 segundo9)
    (incompatible primero17 segundo13)
    (incompatible primero17 segundo28)
    (incompatible primero17 segundo30)
    (incompatible primero17 segundo35)
    (incompatible primero17 segundo42)
    (incompatible primero17 segundo45)
    (incompatible primero18 segundo5)
    (incompatible primero18 segundo6)
    (incompatible primero18 segundo8)
    (incompatible primero18 segundo23)
    (incompatible primero18 segundo29)
    (incompatible primero18 segundo34)
    (incompatible primero18 segundo35)
    (incompatible primero18 segundo36)
    (incompatible primero18 segundo38)
    (incompatible primero18 segundo42)
    (incompatible primero18 segundo46)
    (incompatible primero18 segundo47)
    (incompatible primero19 segundo0)
    (incompatible primero19 segundo17)
    (incompatible primero19 segundo20)
    (incompatible primero19 segundo27)
    (incompatible primero19 segundo31)
    (incompatible primero19 segundo34)
    (incompatible primero19 segundo35)
    (incompatible primero19 segundo37)
    (incompatible primero19 segundo46)
    (incompatible primero20 segundo0)
    (incompatible primero20 segundo2)
    (incompatible primero20 segundo13)
    (incompatible primero20 segundo17)
    (incompatible primero20 segundo18)
    (incompatible primero20 segundo24)
    (incompatible primero20 segundo25)
    (incompatible primero20 segundo26)
    (incompatible primero20 segundo41)
    (incompatible primero20 segundo42)
    (incompatible primero20 segundo43)
    (incompatible primero20 segundo49)
    (incompatible primero21 segundo2)
    (incompatible primero21 segundo5)
    (incompatible primero21 segundo9)
    (incompatible primero21 segundo10)
    (incompatible primero21 segundo18)
    (incompatible primero21 segundo28)
    (incompatible primero21 segundo32)
    (incompatible primero21 segundo36)
    (incompatible primero21 segundo40)
    (incompatible primero21 segundo44)
    (incompatible primero21 segundo45)
    (incompatible primero21 segundo47)
    (incompatible primero22 segundo2)
    (incompatible primero22 segundo8)
    (incompatible primero22 segundo9)
    (incompatible primero22 segundo11)
    (incompatible primero22 segundo12)
    (incompatible primero22 segundo18)
    (incompatible primero22 segundo27)
    (incompatible primero22 segundo28)
    (incompatible primero22 segundo29)
    (incompatible primero22 segundo32)
    (incompatible primero22 segundo36)
    (incompatible primero22 segundo39)
    (incompatible primero22 segundo41)
    (incompatible primero22 segundo47)
    (incompatible primero22 segundo49)
    (incompatible primero23 segundo0)
    (incompatible primero23 segundo4)
    (incompatible primero23 segundo5)
    (incompatible primero23 segundo8)
    (incompatible primero23 segundo9)
    (incompatible primero23 segundo10)
    (incompatible primero23 segundo18)
    (incompatible primero23 segundo21)
    (incompatible primero23 segundo28)
    (incompatible primero23 segundo31)
    (incompatible primero23 segundo33)
    (incompatible primero23 segundo36)
    (incompatible primero23 segundo42)
    (incompatible primero23 segundo46)
    (incompatible primero24 segundo9)
    (incompatible primero24 segundo12)
    (incompatible primero24 segundo22)
    (incompatible primero24 segundo23)
    (incompatible primero24 segundo27)
    (incompatible primero24 segundo29)
    (incompatible primero24 segundo35)
    (incompatible primero25 segundo10)
    (incompatible primero25 segundo17)
    (incompatible primero25 segundo31)
    (incompatible primero25 segundo32)
    (incompatible primero25 segundo33)
    (incompatible primero25 segundo35)
    (incompatible primero25 segundo38)
    (incompatible primero25 segundo40)
    (incompatible primero25 segundo41)
    (incompatible primero25 segundo48)
    (incompatible primero26 segundo4)
    (incompatible primero26 segundo7)
    (incompatible primero26 segundo17)
    (incompatible primero26 segundo18)
    (incompatible primero26 segundo24)
    (incompatible primero26 segundo25)
    (incompatible primero26 segundo34)
    (incompatible primero26 segundo37)
    (incompatible primero26 segundo38)
    (incompatible primero26 segundo44)
    (incompatible primero26 segundo45)
    (incompatible primero26 segundo47)
    (incompatible primero26 segundo48)
    (incompatible primero27 segundo11)
    (incompatible primero27 segundo25)
    (incompatible primero27 segundo28)
    (incompatible primero27 segundo31)
    (incompatible primero27 segundo37)
    (incompatible primero27 segundo39)
    (incompatible primero28 segundo5)
    (incompatible primero28 segundo6)
    (incompatible primero28 segundo7)
    (incompatible primero28 segundo8)
    (incompatible primero28 segundo11)
    (incompatible primero28 segundo20)
    (incompatible primero28 segundo24)
    (incompatible primero28 segundo26)
    (incompatible primero28 segundo29)
    (incompatible primero28 segundo30)
    (incompatible primero28 segundo37)
    (incompatible primero29 segundo1)
    (incompatible primero29 segundo6)
    (incompatible primero29 segundo9)
    (incompatible primero29 segundo18)
    (incompatible primero29 segundo23)
    (incompatible primero29 segundo24)
    (incompatible primero29 segundo33)
    (incompatible primero29 segundo49)
    (incompatible primero30 segundo7)
    (incompatible primero30 segundo12)
    (incompatible primero30 segundo21)
    (incompatible primero30 segundo29)
    (incompatible primero30 segundo32)
    (incompatible primero30 segundo36)
    (incompatible primero30 segundo37)
    (incompatible primero30 segundo39)
    (incompatible primero30 segundo49)
    (incompatible primero31 segundo2)
    (incompatible primero31 segundo11)
    (incompatible primero31 segundo15)
    (incompatible primero31 segundo24)
    (incompatible primero31 segundo28)
    (incompatible primero31 segundo33)
    (incompatible primero31 segundo35)
    (incompatible primero31 segundo37)
    (incompatible primero31 segundo40)
    (incompatible primero31 segundo42)
    (incompatible primero32 segundo1)
    (incompatible primero32 segundo18)
    (incompatible primero32 segundo29)
    (incompatible primero32 segundo35)
    (incompatible primero32 segundo42)
    (incompatible primero32 segundo44)
    (incompatible primero32 segundo47)
    (incompatible primero33 segundo3)
    (incompatible primero33 segundo9)
    (incompatible primero33 segundo10)
    (incompatible primero33 segundo13)
    (incompatible primero33 segundo15)
    (incompatible primero33 segundo27)
    (incompatible primero33 segundo34)
    (incompatible primero33 segundo38)
    (incompatible primero33 segundo44)
    (incompatible primero33 segundo45)
    (incompatible primero34 segundo14)
    (incompatible primero34 segundo20)
    (incompatible primero34 segundo31)
    (incompatible primero34 segundo34)
    (incompatible primero34 segundo43)
    (incompatible primero34 segundo44)
    (incompatible primero34 segundo45)
    (incompatible primero35 segundo4)
    (incompatible primero35 segundo13)
    (incompatible primero35 segundo28)
    (incompatible primero35 segundo29)
    (incompatible primero35 segundo30)
    (incompatible primero35 segundo41)
    (incompatible primero36 segundo1)
    (incompatible primero36 segundo7)
    (incompatible primero36 segundo10)
    (incompatible primero36 segundo16)
    (incompatible primero36 segundo17)
    (incompatible primero36 segundo20)
    (incompatible primero36 segundo23)
    (incompatible primero36 segundo24)
    (incompatible primero36 segundo27)
    (incompatible primero36 segundo45)
    (incompatible primero36 segundo49)
    (incompatible primero37 segundo1)
    (incompatible primero37 segundo7)
    (incompatible primero37 segundo9)
    (incompatible primero37 segundo12)
    (incompatible primero37 segundo21)
    (incompatible primero37 segundo29)
    (incompatible primero37 segundo36)
    (incompatible primero37 segundo39)
    (incompatible primero37 segundo45)
    (incompatible primero38 segundo6)
    (incompatible primero38 segundo10)
    (incompatible primero38 segundo11)
    (incompatible primero38 segundo18)
    (incompatible primero38 segundo23)
    (incompatible primero38 segundo35)
    (incompatible primero38 segundo36)
    (incompatible primero38 segundo41)
    (incompatible primero38 segundo42)
    (incompatible primero38 segundo47)
    (incompatible primero38 segundo48)
    (incompatible primero39 segundo3)
    (incompatible primero39 segundo15)
    (incompatible primero39 segundo17)
    (incompatible primero39 segundo20)
    (incompatible primero39 segundo21)
    (incompatible primero39 segundo31)
    (incompatible primero39 segundo37)
    (incompatible primero39 segundo49)
    (incompatible primero40 segundo1)
    (incompatible primero40 segundo2)
    (incompatible primero40 segundo4)
    (incompatible primero40 segundo6)
    (incompatible primero40 segundo13)
    (incompatible primero40 segundo20)
    (incompatible primero40 segundo31)
    (incompatible primero40 segundo43)
    (incompatible primero40 segundo45)
    (incompatible primero40 segundo48)
    (incompatible primero41 segundo0)
    (incompatible primero41 segundo8)
    (incompatible primero41 segundo13)
    (incompatible primero41 segundo14)
    (incompatible primero41 segundo15)
    (incompatible primero41 segundo19)
    (incompatible primero41 segundo21)
    (incompatible primero41 segundo23)
    (incompatible primero41 segundo24)
    (incompatible primero41 segundo29)
    (incompatible primero41 segundo30)
    (incompatible primero41 segundo36)
    (incompatible primero41 segundo39)
    (incompatible primero41 segundo44)
    (incompatible primero41 segundo47)
    (incompatible primero41 segundo49)
    (incompatible primero42 segundo2)
    (incompatible primero42 segundo3)
    (incompatible primero42 segundo6)
    (incompatible primero42 segundo11)
    (incompatible primero42 segundo15)
    (incompatible primero42 segundo20)
    (incompatible primero42 segundo31)
    (incompatible primero42 segundo32)
    (incompatible primero42 segundo34)
    (incompatible primero42 segundo49)
    (incompatible primero43 segundo4)
    (incompatible primero43 segundo5)
    (incompatible primero43 segundo20)
    (incompatible primero43 segundo23)
    (incompatible primero43 segundo24)
    (incompatible primero43 segundo42)
    (incompatible primero43 segundo46)
    (incompatible primero43 segundo48)
    (incompatible primero44 segundo15)
    (incompatible primero44 segundo20)
    (incompatible primero44 segundo25)
    (incompatible primero44 segundo29)
    (incompatible primero44 segundo31)
    (incompatible primero44 segundo40)
    (incompatible primero44 segundo43)
    (incompatible primero44 segundo46)
    (incompatible primero45 segundo4)
    (incompatible primero45 segundo7)
    (incompatible primero45 segundo8)
    (incompatible primero45 segundo13)
    (incompatible primero45 segundo20)
    (incompatible primero45 segundo41)
    (incompatible primero46 segundo0)
    (incompatible primero46 segundo5)
    (incompatible primero46 segundo19)
    (incompatible primero46 segundo27)
    (incompatible primero46 segundo30)
    (incompatible primero46 segundo31)
    (incompatible primero46 segundo32)
    (incompatible primero46 segundo34)
    (incompatible primero46 segundo38)
    (incompatible primero46 segundo39)
    (incompatible primero46 segundo40)
    (incompatible primero46 segundo43)
    (incompatible primero46 segundo46)
    (incompatible primero46 segundo48)
    (incompatible primero47 segundo1)
    (incompatible primero47 segundo2)
    (incompatible primero47 segundo5)
    (incompatible primero47 segundo7)
    (incompatible primero47 segundo23)
    (incompatible primero47 segundo24)
    (incompatible primero47 segundo27)
    (incompatible primero47 segundo31)
    (incompatible primero47 segundo41)
    (incompatible primero47 segundo42)
    (incompatible primero47 segundo46)
    (incompatible primero47 segundo48)
    (incompatible primero48 segundo3)
    (incompatible primero48 segundo5)
    (incompatible primero48 segundo7)
    (incompatible primero48 segundo21)
    (incompatible primero48 segundo27)
    (incompatible primero48 segundo30)
    (incompatible primero48 segundo31)
    (incompatible primero48 segundo32)
    (incompatible primero48 segundo34)
    (incompatible primero49 segundo3)
    (incompatible primero49 segundo14)
    (incompatible primero49 segundo25)
    (incompatible primero49 segundo36)
    (incompatible primero49 segundo37)
    ; EXTENSION 2
    ; Tipos de los platos
    (es_de_tipo primero0 tipo2)
    (es_de_tipo primero1 tipo0)
    (es_de_tipo primero2 tipo1)
    (es_de_tipo primero3 tipo3)
    (es_de_tipo primero4 tipo0)
    (es_de_tipo primero5 tipo0)
    (es_de_tipo primero6 tipo2)
    (es_de_tipo primero7 tipo1)
    (es_de_tipo primero8 tipo4)
    (es_de_tipo primero9 tipo0)
    (es_de_tipo primero10 tipo0)
    (es_de_tipo primero11 tipo1)
    (es_de_tipo primero12 tipo5)
    (es_de_tipo primero13 tipo4)
    (es_de_tipo primero14 tipo4)
    (es_de_tipo primero15 tipo1)
    (es_de_tipo primero16 tipo0)
    (es_de_tipo primero17 tipo3)
    (es_de_tipo primero18 tipo2)
    (es_de_tipo primero19 tipo1)
    (es_de_tipo primero20 tipo0)
    (es_de_tipo primero21 tipo0)
    (es_de_tipo primero22 tipo2)
    (es_de_tipo primero23 tipo0)
    (es_de_tipo primero24 tipo3)
    (es_de_tipo primero25 tipo1)
    (es_de_tipo primero26 tipo1)
    (es_de_tipo primero27 tipo2)
    (es_de_tipo primero28 tipo3)
    (es_de_tipo primero29 tipo4)
    (es_de_tipo primero30 tipo5)
    (es_de_tipo primero31 tipo3)
    (es_de_tipo primero32 tipo4)
    (es_de_tipo primero33 tipo5)
    (es_de_tipo primero34 tipo5)
    (es_de_tipo primero35 tipo3)
    (es_de_tipo primero36 tipo3)
    (es_de_tipo primero37 tipo1)
    (es_de_tipo primero38 tipo2)
    (es_de_tipo primero39 tipo1)
    (es_de_tipo primero40 tipo5)
    (es_de_tipo primero41 tipo2)
    (es_de_tipo primero42 tipo3)
    (es_de_tipo primero43 tipo3)
    (es_de_tipo primero44 tipo1)
    (es_de_tipo primero45 tipo5)
    (es_de_tipo primero46 tipo4)
    (es_de_tipo primero47 tipo5)
    (es_de_tipo primero48 tipo2)
    (es_de_tipo primero49 tipo5)
    (es_de_tipo segundo0 tipo4)
    (es_de_tipo segundo1 tipo1)
    (es_de_tipo segundo2 tipo3)
    (es_de_tipo segundo3 tipo1)
    (es_de_tipo segundo4 tipo5)
    (es_de_tipo segundo5 tipo4)
    (es_de_tipo segundo6 tipo0)
    (es_de_tipo segundo7 tipo0)
    (es_de_tipo segundo8 tipo1)
    (es_de_tipo segundo9 tipo4)
    (es_de_tipo segundo10 tipo4)
    (es_de_tipo segundo11 tipo0)
    (es_de_tipo segundo12 tipo5)
    (es_de_tipo segundo13 tipo1)
    (es_de_tipo segundo14 tipo3)
    (es_de_tipo segundo15 tipo4)
    (es_de_tipo segundo16 tipo2)
    (es_de_tipo segundo17 tipo0)
    (es_de_tipo segundo18 tipo4)
    (es_de_tipo segundo19 tipo4)
    (es_de_tipo segundo20 tipo2)
    (es_de_tipo segundo21 tipo3)
    (es_de_tipo segundo22 tipo0)
    (es_de_tipo segundo23 tipo3)
    (es_de_tipo segundo24 tipo4)
    (es_de_tipo segundo25 tipo5)
    (es_de_tipo segundo26 tipo2)
    (es_de_tipo segundo27 tipo1)
    (es_de_tipo segundo28 tipo3)
    (es_de_tipo segundo29 tipo2)
    (es_de_tipo segundo30 tipo4)
    (es_de_tipo segundo31 tipo1)
    (es_de_tipo segundo32 tipo3)
    (es_de_tipo segundo33 tipo5)
    (es_de_tipo segundo34 tipo0)
    (es_de_tipo segundo35 tipo0)
    (es_de_tipo segundo36 tipo4)
    (es_de_tipo segundo37 tipo1)
    (es_de_tipo segundo38 tipo1)
    (es_de_tipo segundo39 tipo5)
    (es_de_tipo segundo40 tipo3)
    (es_de_tipo segundo41 tipo3)
    (es_de_tipo segundo42 tipo3)
    (es_de_tipo segundo43 tipo2)
    (es_de_tipo segundo44 tipo2)
    (es_de_tipo segundo45 tipo1)
    (es_de_tipo segundo46 tipo1)
    (es_de_tipo segundo47 tipo4)
    (es_de_tipo segundo48 tipo1)
    (es_de_tipo segundo49 tipo3)
	; EXTENSION 3
    ; Esto se debe hacer por cada plato que deseemos fijar a un dia
    ; en este caso obligaremos a hacer un primero y un segundo un dia de la semana
    (servido_primero lunes)
    (menu_primero lunes primero26)
    (tipo_dia_primero lunes tipo1)
    (preparado primero26)
    (servido_segundo lunes)
    (menu_segundo lunes segundo7)
    (tipo_dia_segundo lunes tipo0)
    (preparado segundo7)
	; EXTENSION 4
    ; Calorias de los primeros platos
    (= (calorias primero0) 1340)
    (= (calorias primero1) 1192)
    (= (calorias primero2) 576)
    (= (calorias primero3) 662)
    (= (calorias primero4) 978)
    (= (calorias primero5) 557)
    (= (calorias primero6) 1217)
    (= (calorias primero7) 976)
    (= (calorias primero8) 1359)
    (= (calorias primero9) 1081)
    (= (calorias primero10) 1180)
    (= (calorias primero11) 1124)
    (= (calorias primero12) 1307)
    (= (calorias primero13) 518)
    (= (calorias primero14) 886)
    (= (calorias primero15) 1031)
    (= (calorias primero16) 711)
    (= (calorias primero17) 508)
    (= (calorias primero18) 616)
    (= (calorias primero19) 632)
    (= (calorias primero20) 822)
    (= (calorias primero21) 1441)
    (= (calorias primero22) 1438)
    (= (calorias primero23) 832)
    (= (calorias primero24) 1495)
    (= (calorias primero25) 1100)
    (= (calorias primero26) 1362)
    (= (calorias primero27) 1105)
    (= (calorias primero28) 1315)
    (= (calorias primero29) 1097)
    (= (calorias primero30) 876)
    (= (calorias primero31) 844)
    (= (calorias primero32) 1479)
    (= (calorias primero33) 952)
    (= (calorias primero34) 1006)
    (= (calorias primero35) 956)
    (= (calorias primero36) 700)
    (= (calorias primero37) 1413)
    (= (calorias primero38) 1123)
    (= (calorias primero39) 1249)
    (= (calorias primero40) 683)
    (= (calorias primero41) 1493)
    (= (calorias primero42) 872)
    (= (calorias primero43) 1491)
    (= (calorias primero44) 510)
    (= (calorias primero45) 948)
    (= (calorias primero46) 711)
    (= (calorias primero47) 722)
    (= (calorias primero48) 646)
    (= (calorias primero49) 828)

    ; Calorias de los segundos platos
    (= (calorias segundo0) 544)
    (= (calorias segundo1) 969)
    (= (calorias segundo2) 1459)
    (= (calorias segundo3) 1482)
    (= (calorias segundo4) 991)
    (= (calorias segundo5) 1453)
    (= (calorias segundo6) 1081)
    (= (calorias segundo7) 852)
    (= (calorias segundo8) 1057)
    (= (calorias segundo9) 585)
    (= (calorias segundo10) 1449)
    (= (calorias segundo11) 1123)
    (= (calorias segundo12) 930)
    (= (calorias segundo13) 1427)
    (= (calorias segundo14) 1266)
    (= (calorias segundo15) 1126)
    (= (calorias segundo16) 883)
    (= (calorias segundo17) 1466)
    (= (calorias segundo18) 729)
    (= (calorias segundo19) 1196)
    (= (calorias segundo20) 1214)
    (= (calorias segundo21) 912)
    (= (calorias segundo22) 1188)
    (= (calorias segundo23) 1276)
    (= (calorias segundo24) 592)
    (= (calorias segundo25) 1198)
    (= (calorias segundo26) 724)
    (= (calorias segundo27) 804)
    (= (calorias segundo28) 1420)
    (= (calorias segundo29) 870)
    (= (calorias segundo30) 1132)
    (= (calorias segundo31) 1155)
    (= (calorias segundo32) 1029)
    (= (calorias segundo33) 780)
    (= (calorias segundo34) 1136)
    (= (calorias segundo35) 519)
    (= (calorias segundo36) 1423)
    (= (calorias segundo37) 1408)
    (= (calorias segundo38) 872)
    (= (calorias segundo39) 979)
    (= (calorias segundo40) 1493)
    (= (calorias segundo41) 820)
    (= (calorias segundo42) 1293)
    (= (calorias segundo43) 922)
    (= (calorias segundo44) 1438)
    (= (calorias segundo45) 1058)
    (= (calorias segundo46) 1239)
    (= (calorias segundo47) 510)
    (= (calorias segundo48) 1023)
    (= (calorias segundo49) 1468)
	; EXTENSION 5
    ; Precios de los primeros platos
    (= (precio_plato primero0) 14)
    (= (precio_plato primero1) 11)
    (= (precio_plato primero2) 12)
    (= (precio_plato primero3) 10)
    (= (precio_plato primero4) 14)
    (= (precio_plato primero5) 4)
    (= (precio_plato primero6) 8)
    (= (precio_plato primero7) 11)
    (= (precio_plato primero8) 6)
    (= (precio_plato primero9) 1)
    (= (precio_plato primero10) 1)
    (= (precio_plato primero11) 0)
    (= (precio_plato primero12) 2)
    (= (precio_plato primero13) 13)
    (= (precio_plato primero14) 12)
    (= (precio_plato primero15) 1)
    (= (precio_plato primero16) 12)
    (= (precio_plato primero17) 7)
    (= (precio_plato primero18) 2)
    (= (precio_plato primero19) 12)
    (= (precio_plato primero20) 14)
    (= (precio_plato primero21) 4)
    (= (precio_plato primero22) 12)
    (= (precio_plato primero23) 14)
    (= (precio_plato primero24) 13)
    (= (precio_plato primero25) 11)
    (= (precio_plato primero26) 7)
    (= (precio_plato primero27) 12)
    (= (precio_plato primero28) 11)
    (= (precio_plato primero29) 5)
    (= (precio_plato primero30) 10)
    (= (precio_plato primero31) 10)
    (= (precio_plato primero32) 1)
    (= (precio_plato primero33) 0)
    (= (precio_plato primero34) 12)
    (= (precio_plato primero35) 8)
    (= (precio_plato primero36) 11)
    (= (precio_plato primero37) 6)
    (= (precio_plato primero38) 4)
    (= (precio_plato primero39) 2)
    (= (precio_plato primero40) 14)
    (= (precio_plato primero41) 12)
    (= (precio_plato primero42) 2)
    (= (precio_plato primero43) 1)
    (= (precio_plato primero44) 11)
    (= (precio_plato primero45) 14)
    (= (precio_plato primero46) 9)
    (= (precio_plato primero47) 8)
    (= (precio_plato primero48) 13)
    (= (precio_plato primero49) 4)
    ; Precios de los primeros platos
    (= (precio_plato segundo0) 12)
    (= (precio_plato segundo1) 4)
    (= (precio_plato segundo2) 8)
    (= (precio_plato segundo3) 1)
    (= (precio_plato segundo4) 11)
    (= (precio_plato segundo5) 13)
    (= (precio_plato segundo6) 5)
    (= (precio_plato segundo7) 3)
    (= (precio_plato segundo8) 3)
    (= (precio_plato segundo9) 1)
    (= (precio_plato segundo10) 9)
    (= (precio_plato segundo11) 13)
    (= (precio_plato segundo12) 12)
    (= (precio_plato segundo13) 2)
    (= (precio_plato segundo14) 13)
    (= (precio_plato segundo15) 1)
    (= (precio_plato segundo16) 2)
    (= (precio_plato segundo17) 9)
    (= (precio_plato segundo18) 7)
    (= (precio_plato segundo19) 14)
    (= (precio_plato segundo20) 11)
    (= (precio_plato segundo21) 13)
    (= (precio_plato segundo22) 11)
    (= (precio_plato segundo23) 5)
    (= (precio_plato segundo24) 6)
    (= (precio_plato segundo25) 14)
    (= (precio_plato segundo26) 11)
    (= (precio_plato segundo27) 1)
    (= (precio_plato segundo28) 14)
    (= (precio_plato segundo29) 9)
    (= (precio_plato segundo30) 5)
    (= (precio_plato segundo31) 11)
    (= (precio_plato segundo32) 6)
    (= (precio_plato segundo33) 5)
    (= (precio_plato segundo34) 13)
    (= (precio_plato segundo35) 2)
    (= (precio_plato segundo36) 3)
    (= (precio_plato segundo37) 3)
    (= (precio_plato segundo38) 12)
    (= (precio_plato segundo39) 6)
    (= (precio_plato segundo40) 11)
    (= (precio_plato segundo41) 6)
    (= (precio_plato segundo42) 12)
    (= (precio_plato segundo43) 8)
    (= (precio_plato segundo44) 1)
    (= (precio_plato segundo45) 10)
    (= (precio_plato segundo46) 10)
    (= (precio_plato segundo47) 3)
    (= (precio_plato segundo48) 12)
    (= (precio_plato segundo49) 9)

    (= (precio_total) 0)


    )

  (:metric 
    minimize (precio_total)
    )

  (:goal (forall (?d - dia)
                 (and (servido_primero ?d)
                      (servido_segundo ?d)
                      )
                 )
         )
  )
